### ISSUE TITLE
Right-clicking a helmet in your hand whilst an emote is active will remove the helmet from your inventory entirely

### ISSUE THREAD

**Issue by baailey** [yapzhenyie/GadgetsMenu#815]
**Describe the bug**
If you have an Emote equipped and you try to apply a helmet via right-clicking whilst holding said helmet, it will remove the helmet from your inventory and place the Emote in your hand instead with a duplicate.

**To Reproduce**
1. Hold a helmet in your hand
2. Open /gmenu main
3. Click 'Emotes'
4. Equip any Emote
5. Right-click the helmet in your hand whilst the Emote is on 'cooldown'

**Expected behavior**
There are 3 options I expect:
1. Right-clicking the helmet will auto drop said helmet onto the ground
2. It will send an error message saying 'you have an Emote equipped'
3. It will auto disable the Emote and equip the helmet

**Further Information (please complete the following information):**
 - Server Version: git-Tuinity-"576e2cc" (MC: 1.16.3)
 - GadgetsMenu Version: 4.6.3

**Screenshots**
Here is a video: https://youtu.be/q35yWwEVUaE

**Additional Information**
None.

**Comment by OnlyNoobDied** [comment]
@baailey I'm not be able to access to the youtube video.

**Comment by baailey** [comment]
Apologies, should be all good now

**Comment by OnlyNoobDied** [comment]
@baailey May I have your spigot profile name for verification?

**Comment by baailey** [comment]
I am a manager on the server, I did not buy it myself. The Spigot profile should be SkyServers, but I can have the Owner message you on your Discord server if you'd like further verification.

**Comment by OnlyNoobDied** [comment]
Do you have any plugin that is handling "Hat" feature? Basically when player right-click a helmet, it will replace the helmet slot of player's inventory. I think that this plugin might conflicting with GadgetsMenu.

**Comment by baailey** [comment]
The plugin conflicting is AdvancedEnchantments

**Comment by OnlyNoobDied** [comment]
I perhaps this issue do not have to solved by me.

**Comment by baailey** [comment]
I can submit a bug report to AE and see what the developer says.

**Comment by OnlyNoobDied** [comment]
Any news?

**Comment by baailey** [comment]
Apologies for the delay, have just submitted the bug report which you can find [here](https://github.com/GC-spigot/AdvancedEnchantments/issues/1569)

**Comment by Insprill** [comment]
Hey - Advanced Enchantments dev here. This has been fixed on our side for the next update so this can be closed.

**Comment by yapzhenyie** [comment]
> Hey - Advanced Enchantments dev here. This has been fixed on our side for the next update so this can be closed.

Good to hear that, thank you
