### ISSUE TITLE
My friends pet cat is bugged.

### ISSUE THREAD

**Issue by dazorpad** [yapzhenyie/GadgetsMenu#820]
Before the server restarted, my friend had a pet cat at the spawn. After the server restarted, my friend had two pet cats. Now that he is logged off, the cat is still there. I have tried to disable pets and it still was there.

Is there any command that can reset the cosmetics, because, after many restarts, his pet cat is still there?

**Comment by yapzhenyie** [comment]
This issue only occur when you use the Free version of GadgetsMenu. You will be able to kill the pet through the command or manually kill it by sword.

**Comment by dazorpad** [comment]
So I cant do anything about it? I have to purchase the other version to kill it?

**Comment by dazorpad** [comment]
Does this mean other players can kill peoples pets?

**Comment by yapzhenyie** [comment]
> Does this mean other players can kill peoples pets?

If you found that there are duplicate pets after server restart, you can kill the pet manually through `/kill` command or kill it by sword.
