### ISSUE TITLE
[PREMIUM VER] Task generated an exception

### ISSUE THREAD

**Issue by DiegoDaniel** [yapzhenyie/GadgetsMenu#824]
Using the spiderman suit, i got this error on console. Not critical but idk how much damage can this cause.

https://pastebin.com/Fzfv6CtM

Plugin ver: 4.6.3 (premium)
Java 11
Minecraft 1.16.4

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
