### ISSUE TITLE
MysteryBox bug...............

### ISSUE THREAD

**Issue by Xiaojin-serv** [yapzhenyie/GadgetsMenu#826]
Is there something wrong with my config?
version: Paper 1.12.2
![2021-01-03_14 31 20](https://user-images.githubusercontent.com/69352997/103473199-eb3b4b00-4dd0-11eb-8916-43b86124b465.png)

**Comment by yapzhenyie** [comment]
The height of the hologram can be changed inside `mystery boxes.yml` file.

**Comment by Xiaojin-serv** [comment]
> 
> 
> The height of the hologram can be changed inside `mystery boxes.yml` file.
