### ISSUE TITLE
GadgetsMenu is not compatible with Protocollib build #491 and above

### ISSUE THREAD

**Issue by FaberoM** [yapzhenyie/GadgetsMenu#827]
**Describe the bug**
Protocollib recently had a commit that replaced CGLib with ByteBuddy which renamed some classes. See https://github.com/dmulloy2/ProtocolLib/commit/b54dd49426f1c4cb5a15d1702a4803af1846847e

That change broke GadgetsMenu which is looking for class `com/comphenix/net/sf/cglib/proxy/Factory` but should now use `ByteBuddyGenerated` class instead.

**To Reproduce**
1. Use Protocollib build 491 or above with GadgetsMenu
2. See error

**Expected behavior**
No errors would show

**Further Information (please complete the following information):**
 - Server Version: Paper 1.16.4 build 399
 - GadgetsMenu Version: 4.6.3
 - Console stack trace: https://paste.md-5.net/quhoyicuga.bash

**Comment by yapzhenyie** [comment]
I had received several report regarding to this, and I will look for a solution. You can use the older version of ProtocolLib before the issue is solved.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
