### ISSUE TITLE
LuckPerms x GadgetsMenu

### ISSUE THREAD

**Issue by Reiamsei** [yapzhenyie/GadgetsMenu#830]
**Describe the bug**
I felt in love with your permission nodes and thought it would be awesome to implement them into my Luckperms Rank system.
after 1-2 hours of implement everything i recognized, that it isnit working.
Do I need to enable anything ?
I Have the Premium Version.

**Further Information (please complete the following information):**
 - Server Version: [1,16,4]
 - GadgetsMenu Version: [[Premium] 4.6.5]

**Comment by yapzhenyie** [comment]
Can you explain more details about the issue you have? I'm not very sure what issue you're having.

**Comment by Reiamsei** [comment]
i was just dumb I´m sorry for wasting time
