### ISSUE TITLE
Gadgetsmenu have more Permissions then Gadgetsmenu Premium ?

### ISSUE THREAD

**Issue by Reiamsei** [yapzhenyie/GadgetsMenu#831]
Why I have mor Permissions in the Free Version then in die Premium ?
i only get permissions for gadgetsmenu.gadgets..... ,banners, hats and animated hats the Free version ?
Miniatures have only the * permission
pls fix this.
Minecrfat Version 1.16.4
newest version of your plugin.

**Comment by yapzhenyie** [comment]
You can check the permissions here.
https://github.com/yapzhenyie/GadgetsMenu/wiki/Permissions

**Comment by Reiamsei** [comment]
> You can check the permissions here.
> https://github.com/yapzhenyie/GadgetsMenu/wiki/Permissions

I know the permissions...
in the free version I have more then in the Premium... why ?

**Comment by yapzhenyie** [comment]
You can use the rest of the permissions. I think you did something wrong in LuckPerms perms.

**Comment by Reiamsei** [comment]
> You can use the rest of the permissions. I think you did something wrong in LuckPerms perms.
> All permissions are work as usual.

when i change the plugin to the free version it works directly!
there is an issue
also the nether start don´t appear for non Op...

everything works in the free version
only the Premium version is buggy

**Comment by yapzhenyie** [comment]
> > You can use the rest of the permissions. I think you did something wrong in LuckPerms perms.
> > All permissions are work as usual.
> 
> when i change the plugin to the free version it works directly!
> there is an issue
> also the nether start don´t appear for non Op...
> 
> everything works in the free version
> only the Premium version is buggy

In order to receive the nether star, you need `gadgetsmenu.menuselector` permission.

**Comment by yapzhenyie** [comment]
Any updates on this?

**Comment by Refaldy03** [comment]
then how do you get the default rank to only use emojis but if you want to use another gadget you have to upgrade your rank first before using the gadget?

**Comment by yapzhenyie** [comment]
> then how do you get the default rank to only use emojis but if you want to use another gadget you have to upgrade your rank first before using the gadget?

Cosmetic items are accessible via permission. All players can purchase the cosmetic item via Mystery Dust or get it from opening Mystery Box. You can only either disable the purchase option or `can be found` option in config, but you cannot specify which group of people cannot use certain cosmetic items until they are in another group.
