### ISSUE TITLE
Hats/Heads bug

### ISSUE THREAD

**Issue by Maroon28** [yapzhenyie/GadgetsMenu#832]
**Describe the bug**
Basically, you can replicate any hat cosmetic and obtain it as a regular player head.

**To Reproduce**
1. Go to any hat menu
2. Equip a hat
3. Make sure a regular helmet is in your hotbar. Then right click the helmet while the hat is on.
4. You'll see the hat jump into your hotbar instead of the helmet. 
5. The hat is a permanent head now. You can place it down or sell it.  

**Expected behavior**
The hat shouldn't be placeable/sellable.

**Further Information (please complete the following information):**
 - Server Version: 1.16.4
 - GadgetsMenu Version: 4.6.3

**Screenshots**
I don't have screenshots, but I recorded a video.  https://youtu.be/oW-JEYe4w6c

**Comment by yapzhenyie** [comment]
Do you have any plugin that has a feature "equip hat with right-clicking"? This usually causing by other plugin.

**Comment by Maroon28** [comment]
> Do you have any plugin that has a feature "equip hat with right-clicking"? This usually causing by other plugin.

As far as I know, its a vanilla feature. If you shift-right click a hat it auto equips.

**Comment by yapzhenyie** [comment]
> > Do you have any plugin that has a feature "equip hat with right-clicking"? This usually causing by other plugin.
> 
> As far as I know, its a vanilla feature. If you shift-right click a hat it auto equips.

The vanilla minecraft feature will only equip helmet with right-click when the player's helmet slot is empty.
This issue is caused by plugin conflict. I assuming you have other plugins that will equip helmet with right-clicking.

I had received several same issue before this, and it was caused by CMI plugin. However, CMI has already fixed this issue.
