### ISSUE TITLE
Plugin error on join

### ISSUE THREAD

**Issue by Maroon28** [yapzhenyie/GadgetsMenu#833]
**Describe the bug**
Throws an error in the console whenever a player joins the server.

**To Reproduce**
1. Happens on server join. Not sure what the actual reproduction steps are.

**Expected behavior**
The plugin should not spam the console

**Further Information (please complete the following information):**
 - 1.16.4
 - GadgetsMenu Version: 4.6.5 (up to date as of writing this)
 - Console stack trace if have: https://pastebin.com/trZayN0u

**Comment by yapzhenyie** [comment]
May I know what's your spigot profile name? I need to verify the buyer identity.
