### ISSUE TITLE
how to connect mysql?

### ISSUE THREAD

**Issue by GreenRiceCake** [yapzhenyie/GadgetsMenu#837]
I have installed MySql and run the server, but the plugin does not connect to MySql. how to connect mysql?

- server version [1.16.5]
- gadgetsmenu version [4.4.6]free
- console : Failed to connect to MySQL database!

**Comment by yapzhenyie** [comment]
That's not how MySQL works. You need a MySQL server and setup the settings in `config.yml` to get it connected to MySQL database.

**Comment by GreenRiceCake** [comment]
Thank you! I solved this problem!

**Comment by GreenRiceCake** [comment]
Hey i have more question

I have seen the MySQL database and the plugin connect successfully.
However, items are still not paid to the default user.

**Comment by Sparxez** [comment]
> Hey i have more question
> 
> I have seen the MySQL database and the plugin connect successfully.
> However, items are still not paid to the default user.

This has nothing to do with MySQL - you need to edit config.yml and mystery boxes.yml. 'Execute-Command' needs to be changed to your permission plugins command to add a permission to a player.

**Comment by yapzhenyie** [comment]
https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from-mystery-boxes-but-they-still-cant-use-that-item

**Comment by GreenRiceCake** [comment]
Thank you! I solved this problem.

**Comment by Sparxez** [comment]
Great! :D
