### ISSUE TITLE
How to turn off all gadgets? 

### ISSUE THREAD

**Issue by FadelessBanjo** [yapzhenyie/GadgetsMenu#839]
How can I have it that when a player joins the server, that player won't already have all the cosmetics?

**Comment by yapzhenyie** [comment]
Player normally won't have all cosmetics unlocked unless you gave them the permission of he is op.

**Comment by FadelessBanjo** [comment]
> Player normally won't have all cosmetics unlocked unless you gave them the permission of he is op.

Hmm ok, Do you know what permission would it be that would make players have all the cosmetics?

**Comment by yapzhenyie** [comment]
perhaps you gave them permission `*` or `gadgetsmenu.*`. This will unlock all the cosmetic items.
