### ISSUE TITLE
Permission bug?

### ISSUE THREAD

**Issue by Peanutismo123** [yapzhenyie/GadgetsMenu#840]
so, when a player joins they do not get the boz in the inventory where you select gadgets, they also cant open mystery vaults they click on it and they cant even when i give them evry gadgetsmenu permission, there is no you dont have a permission massage anything

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: [paper 1.8.8]
 - GadgetsMenu Version: 4.4.3
 - Console stack trace if have. - i dont
**Screenshots**
Ithere is nothing to screenshot

**Additional Information**
thats all i dont realy think its beacose of permissions, or am i just blind

**Comment by yapzhenyie** [comment]
https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-why-can-non-op-players-not-open-the-mystery-vault
