### ISSUE TITLE
MySQL not working 

### ISSUE THREAD

**Issue by SideWayy** [yapzhenyie/GadgetsMenu#841]
**Describe the bug**
I tried to connect the plugin to a MySQL Server and it doesn't work.

**To Reproduce**
1. Go to 'server\plugins\GadgetsMenu
2. Click on 'config.yml'
3. Enable MySQL put in all info [hostname, username, port, db, pass]
4. this error https://pastebin.com/qaTTBSpU

**Expected behavior**
I expected it to connect and save player data to the server so I can use on my BungeeCord network but sadly it didn't work.

**Further Information (please complete the following information):**
 - Server Version: [1.8.8] this .jar to be specific https://getbukkit.org/get/hNiHm0tuqAg1Xg7w7zudk63uHr0xo48D
 - GadgetsMenu Version: [4.4.7]
 - Console stack trace: https://pastebin.com/qaTTBSpU

**Comment by yapzhenyie** [comment]
Is your mysql info setup correctly?

**Comment by SideWayy** [comment]
Yes I'm 100% sure I set it up correctly and double checked but still nothing

**Comment by yapzhenyie** [comment]
Try use another user & password for authentication.

**Comment by SideWayy** [comment]
still same error I tried different connections and reinstalling MySQL and its not working

**Comment by yapzhenyie** [comment]
Since you're using your own device to run MySQL, therefore there are several setting you have to set.
You can check this article for more details.
https://stackoverflow.com/questions/50505042/mysqlnontransientconnectionexception-client-does-not-support-authentication-pro

**Comment by SideWayy** [comment]
great! it worked. thx for the support!

**Comment by SideWayy** [comment]
great it worked! thx for the support

**Comment by yapzhenyie** [comment]
Nice :D
