### ISSUE TITLE
Allow HD heads/education.minecraft.net links

### ISSUE THREAD

**Issue by untuned** [yapzhenyie/GadgetsMenu#843]
**Is your feature request related to a problem? Please describe.**
Using the Education version of Minecraft, you are able to upload HD head designs and access them in vanilla Minecraft.

**Describe the solution you'd like**
Allow the usage of `education.minecraft.net` links in the custom hats texture option, or allow pasting the base64 encoded value instead.

**Describe alternatives you've considered**
There are no alternatives since it is not possible on the normal version of Minecraft without texture packs.

**Comment by yapzhenyie** [comment]
You can upload the texture head to http://textures.minecraft.net

Custom texture head can be found at https://minecraft-heads.com/custom-heads

**Comment by untuned** [comment]
> You can upload the texture head to http://textures.minecraft.net
> 
> Custom texture head can be found at https://minecraft-heads.com/custom-heads

Correct, if it were a normal head. These instead use HD textures at 512x512, and are hosted on the education website. It's not possible to upload them to `textures.minecraft.net`.

**Comment by yapzhenyie** [comment]
Is minecraft allow to have HD texture in java edition?

**Comment by untuned** [comment]
> Is minecraft allow to have HD texture in java edition?

By uploading it to `education.minecraft.net` and using a website like https://hdheadgenerator.glitch.me/, absolutely. It will give you a command to run that allows you to get it in your inventory, and it supports up to 512x512 per side which allows a lot more customizability.

**Comment by untuned** [comment]
This was patched in 1.17.
