### ISSUE TITLE
Main menu bugs by opening

### ISSUE THREAD

**Issue by Jeroen123TC** [yapzhenyie/GadgetsMenu#850]
**Describe the bug**
if you try to open the main menu looking at a block then the menu works fine, but if you look at the sky the menu items are buggy and you can't properly select cosmetics

**To Reproduceer**
No errors

**Expected behavior**
The main menu must work fine if you open it when you look to the air.

**Further Information (please complete the following information):**
 - Server Version: [paper 1.16.5
 - GadgetsMenu Version: [4.4.9]
 

https://imgur.com/gallery/5BCDP7H

**Comment by yapzhenyie** [comment]
Ok, I will take a look and try to fix this issue.

**Comment by Jeroen123TC** [comment]
Players use the launcher 1.16.5

**Comment by Jeroen123TC** [comment]
I use the free version of the plugin

**Comment by Jeroen123TC** [comment]
Hey, is there any progress?

**Comment by yapzhenyie** [comment]
> Hey, is there any progress?

I'm so sorry for late reply, I was busy doing my work stuff.

I suspected that this issue is caused by 3rd plugin, can you try not to use Ender Chest as the menu item?

**Comment by yapzhenyie** [comment]
Or can you give me the whole GadgetsMenu folder, so I can test it using your configuration.

**Comment by Jeroen123TC** [comment]
[GadgetsMenu.zip](https://github.com/yapzhenyie/GadgetsMenu/files/6528471/GadgetsMenu.zip)

this is my gadgets menu folder

**Comment by Jeroen123TC** [comment]
I hope you can find the problem :D

**Comment by yapzhenyie** [comment]
> I hope you can find the problem :D

Are you using GadgetsMenu original menu item to open the menu? Seems like you are not

**Comment by Jeroen123TC** [comment]
No i am using the bossshop addon GUIshopManager that connected to the command form gadgetsmenu

**Comment by yapzhenyie** [comment]
> No i am using the bossshop addon GUIshopManager that connected to the command form gadgetsmenu

that might be the issue. Try naming the menu to other name. I think the issue is GUIshopManager menu item has the same name as menu item setting in GadgetsMenu config.yml file.

**Comment by Jeroen123TC** [comment]
Yess that works better, thanks for your time man!
