### ISSUE TITLE
Paintball gun bug when hit a librarian table

### ISSUE THREAD

**Issue by Serial1990** [yapzhenyie/GadgetsMenu#855]
**Describe the bug**
When i hit a librarian table in which there is a book, the book pops out.

**To Reproduce**
1. select the Paintball Gun
2. Hit a librarian table with the Paintball Gun
3. The book pops out.

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: Paper 1.16.5 #569
 - GadgetsMenu Version: 4.6.7

**Comment by yapzhenyie** [comment]
> **Describe the bug**
> When i hit a librarian table in which there is a book, the book pops out.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. select the Paintball Gun
> 2. Hit a librarian table with the Paintball Gun
> 3. The book pops out.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Further Information (please complete the following information):**
> 
> * Server Version: Paper 1.16.5 #569
> * GadgetsMenu Version: 4.6.7

You can set those blocks you do not want to be painted. You can check gadgets.yml file.
```
      Paintball Gun:
        Name: '&aPaintball Gun Gadget'
        Material: DIAMOND_HORSE_ARMOR
        Radius: 3
        Blacklist:
        - SAND
        - GRAVEL
        - SPAWNER
```
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by Serial1990** [comment]
Thanks that solves our problem. :)
