### ISSUE TITLE
Mystery box broadcast still appearing server-wide for vanished users

### ISSUE THREAD

**Issue by baailey** [yapzhenyie/GadgetsMenu#857]
**Describe the bug**
Users in vanish are still receiving mystery boxes even after this issue was supposedly fixed.

**To Reproduce**
1. Go vanish (using PremiumVanish 2.6.15)
2. Find a mystery box

**Expected behavior**
[As described in this screenshot.](https://i.imgur.com/rWIoCYM.png)

**Further Information (please complete the following information):**
 - Server Version: git-Airplane-"fad74c2" (MC: 1.16.5)
 - GadgetsMenu Version: 4.6.9

**Screenshots**
https://gyazo.com/714dfb8d1106ffce36aa6f3fa9d1bb19 (taken 20 minutes ago)
https://i.imgur.com/5etAKCh.png (this was taken last month)

**Comment by yapzhenyie** [comment]
May I know can both players able to see each other?

**Comment by baailey** [comment]
kira11621 and crackerjack27 can see each other, but Han_Chloe who reacted to crackerjack27 finding a mystery box cannot see anyone.

**Comment by baailey** [comment]
This is still an issue if not aware.

**Comment by baailey** [comment]
Unsure if this issue is being looked into, or if you're able to implement a fix at all, but the easiest and quickest solution (if this is a tricky situation) is to implement a permission for actually receiving a mystery box. The vanish plugin I'm using supports running commands when the user vanishes and unvanishes, so personally I can have it set and unset the permission when they do either. LuckPerms also supports adding context to a permission, so players can have the permission work, or not work, if they're detected as vanish. Just an idea!

**Comment by sannielollie** [comment]
Having the same issue too, still waiting for a fix.

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.
