### ISSUE TITLE
Entity threw exception at world:-5901.882333530592,63.0,-1052.1005954425127

### ISSUE THREAD

**Issue by baailey** [yapzhenyie/GadgetsMenu#859]
**Describe the bug**
10.07 18:48:30 [Server] ERROR Entity threw exception at world:-5901.882333530592,63.0,-1052.1005954425127
10.07 18:48:30 [Server] INFO java.lang.NoSuchMethodError: 'net.minecraft.world.level.pathfinder.PathEntity net.minecraft.world.entity.ai.navigation.NavigationAbstract.k()'
10.07 18:48:30 [Server] INFO at com.yapzhenyie.GadgetsMenu.nms.v1_17_R1.pets.entity.types.EntityRabbitPet.mobTick(EntityRabbitPet.java:110) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:846) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3151) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.world.entity.Mob.aiStep(Mob.java:621) ~[?:?]
10.07 18:48:30 [Server] INFO at com.yapzhenyie.GadgetsMenu.nms.v1_17_R1.pets.entity.types.EntityRabbitPet.movementTick(EntityRabbitPet.java:127) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2877) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.world.entity.Mob.tick(Mob.java:389) ~[?:?]
10.07 18:48:30 [Server] INFO at com.yapzhenyie.GadgetsMenu.nms.v1_17_R1.pets.entity.EntityPet.tick(EntityPet.java:261) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1162) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:989) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:821) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:40) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
10.07 18:48:30 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:802) ~[?:?]
10.07 18:48:30 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1613) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
10.07 18:48:30 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
10.07 18:48:30 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1465) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
10.07 18:48:30 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1261) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
10.07 18:48:30 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Tuinity-"2310a94"]
10.07 18:48:30 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

**Further Information (please complete the following information):**
 - Server Version: git-Tuinity-"2310a94" (MC: 1.17.1)
 - GadgetsMenu Version: 5.0.2

**Comment by yapzhenyie** [comment]
This issue only exists in paper server, therefore have to wait for the fixes.

**Comment by baailey** [comment]
Oh, I see. Do you know if there is an open issue I can keep an eye on?

**Comment by yapzhenyie** [comment]
> Oh, I see. Do you know if there is an open issue I can keep an eye on?

nope, I think they need more time to do bug fixes and patches.

**Comment by yapzhenyie** [comment]
> Oh, I see. Do you know if there is an open issue I can keep an eye on?

Sorry, to clarify the error again. This issue is caused by spigot and paper are not referring the same version of mojang patches. In short, spigot does not update the mojang patches. I will try to fix this issue asap.

**Comment by baailey** [comment]
Awesome, thanks

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
