### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.PacketPlayOutMount

### ISSUE THREAD

**Issue by baailey** [yapzhenyie/GadgetsMenu#862]
**Describe the bug**
19.07 17:29:46 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.PacketPlayOutMount
19.07 17:29:46 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
19.07 17:29:46 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
19.07 17:29:46 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
19.07 17:29:46 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
19.07 17:29:46 [Server] WARN at java.base/java.lang.Class.forName(Class.java:375)
19.07 17:29:46 [Server] WARN at com.yapzhenyie.GadgetsMenu.utils.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:700)
19.07 17:29:46 [Server] WARN at com.yapzhenyie.GadgetsMenu.nms.NMSManager.setPassenger(NMSManager.java:100)
19.07 17:29:46 [Server] WARN at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetCowboy.onClick(GadgetCowboy.java:39)
19.07 17:29:46 [Server] WARN at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.Gadget$GadgetListener.onPlayerActivateGadget(Gadget.java:217)
19.07 17:29:46 [Server] WARN at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
19.07 17:29:46 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
19.07 17:29:46 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
19.07 17:29:46 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
19.07 17:29:46 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:538)
19.07 17:29:46 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501)
19.07 17:29:46 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:496)
19.07 17:29:46 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492)
19.07 17:29:46 [Server] WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1853)
19.07 17:29:46 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
19.07 17:29:46 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
19.07 17:29:46 [Server] WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
19.07 17:29:46 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
19.07 17:29:46 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
19.07 17:29:46 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
19.07 17:29:46 [Server] WARN at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1407)
19.07 17:29:46 [Server] WARN at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
19.07 17:29:46 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
19.07 17:29:46 [Server] WARN at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1385)
19.07 17:29:46 [Server] WARN at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1378)
19.07 17:29:46 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
19.07 17:29:46 [Server] WARN at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1354)
19.07 17:29:46 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265)
19.07 17:29:46 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
19.07 17:29:46 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: git-Tuinity-"ce43ccd" (MC: 1.17.1)
 - GadgetsMenu Version: 5.0.3

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
