### ISSUE TITLE
GadgetsMenu failed main thread check: Asynchronous entity ticklist removal

### ISSUE THREAD

**Issue by baailey** [yapzhenyie/GadgetsMenu#865]
**Describe the bug**
29.07 12:08:24 [Server] FATAL Thread Craft Scheduler Thread - 1184 - GadgetsMenu failed main thread check: Asynchronous entity ticklist removal
29.07 12:08:24 [Server] INFO java.lang.Throwable: null
29.07 12:08:24 [Server] INFO at com.tuinity.tuinity.util.TickThread.ensureTickThread(TickThread.java:26) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.remove(EntityTickList.java:26) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTickingEnd(ServerLevel.java:2355) ~[?:?]
29.07 12:08:24 [Server] INFO at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2339) ~[?:?]
29.07 12:08:24 [Server] INFO at net.minecraft.world.level.entity.PersistentEntitySectionManager.stopTicking(PersistentEntitySectionManager.java:197) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.onRemove(PersistentEntitySectionManager.java:524) ~[?:?]
29.07 12:08:24 [Server] INFO at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4101) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at net.minecraft.world.entity.Entity.remove(Entity.java:596) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at net.minecraft.world.entity.Entity.discard(Entity.java:578) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.remove(CraftEntity.java:660) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetBatLauncher.onHit(GadgetBatLauncher.java:153) ~[?:?]
29.07 12:08:24 [Server] INFO at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetBatLauncher.access$2(GadgetBatLauncher.java:123) ~[?:?]
29.07 12:08:24 [Server] INFO at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetBatLauncher$1.run(GadgetBatLauncher.java:76) ~[?:?]
29.07 12:08:24 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Tuinity-"e4b0922"]
29.07 12:08:24 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
29.07 12:08:24 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
29.07 12:08:24 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

**Further Information (please complete the following information):**
 - Server Version: git-Tuinity-"e4b0922" (MC: 1.17.1) 
 - GadgetsMenu Version: 5.0.4

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
