### ISSUE TITLE
Mystery Vault GUI

### ISSUE THREAD

**Issue by FantonFancy** [yapzhenyie/GadgetsMenu#869]
Hello Dev! is it possible to edit this GUI?
![image](https://user-images.githubusercontent.com/70339861/128791585-22572b51-7b5d-49e3-8a66-de20c50627a7.png)

Also how can i edit these
![image](https://user-images.githubusercontent.com/70339861/128792995-e31b44bc-1877-43ba-8590-13fbf796b51c.png)

**Comment by yapzhenyie** [comment]
Most of the menu item settings can be modify in `messages.yml` file.
