### ISSUE TITLE
Asynchronous entity ticklist removal java.lang.Throwable: null

### ISSUE THREAD

**Issue by DarkyCat** [yapzhenyie/GadgetsMenu#871]
**Describe the bug**

**To Reproduce**
https://mcpaste.io/42ffdc62264c875a
https://mcpaste.io/dbdaf22da38e346b [5.0.4]

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: [1.17.1]
 - GadgetsMenu Version: [5.0.5 and 5.0.4]
 - Console stack trace if have.

**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update and keep me posted if the issue is fixed.

**Comment by DarkyCat** [comment]
Yes it is fixed (Spiderman suit)

**Comment by DarkyCat** [comment]
https://mcpaste.io/42ffdc62264c875a - I still do not understand why this error occurred

**Comment by DarkyCat** [comment]
After the 5.0.6 update, it disappeared
