### ISSUE TITLE
Kawarimi no jutsu bug

### ISSUE THREAD

**Issue by DarkyCat** [yapzhenyie/GadgetsMenu#872]
**Describe the bug**
Blocks do not disappear and remain on the spawn. So you can build up the entire spawn

**To Reproduce**
1. You need to log in with two accounts.
2. After putting on a "Kawarimi no jutsu" bug from one
3. and immediately another "Kawarimi no jutsu" on him From the second account

**Further Information (please complete the following information):**
 - Server Version: [1.17.1]
 - GadgetsMenu Version: [5.0.6]
 - No console error

**Screenshots**
Video: https://litter.catbox.moe/pwp3sl.mp4

**Comment by yapzhenyie** [comment]
This issue will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
