### ISSUE TITLE
Adjustable time zone

### ISSUE THREAD

**Issue by InFiniityxSweety** [yapzhenyie/GadgetsMenu#873]
**Is your feature request related to a problem? Please describe.**

My server time zone is CEST and when I create a Mystery Box it says EDT as the time zone

**Describe the solution you'd like**

A setting in the config to set the time zone and where you can set whether the time is displayed in 12 hour intervals or 24 hour intervals

**Describe alternatives you've considered**

The plugin could get the server time itself

**Additional context**

Server time zone: https://prnt.sc/1q8e6cx
Plugin time zone: https://prnt.sc/1q8ebwo

**Comment by yapzhenyie** [comment]
I will considering on this and plan to add an option to change the time zone in future update.

**Comment by yapzhenyie** [comment]
This feature is added in the next update. Please check for new update.
