### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by baailey** [yapzhenyie/GadgetsMenu#874]
**Describe the bug**
Error when trying to open a mystery box at a mystery vault

**To Reproduce**
1. Not sure really, just tried opening a mystery box

**Expected behavior**
It shouldn't cause an error

**Further Information (please complete the following information):**
 - Server Version: git-Airplane-"ec7d3d0" (MC: 1.17.1)
 - GadgetsMenu Version: 5.0.6
 - https://paste.gg/p/anonymous/cade2b732d0b4c5392df650780b68a14

**Comment by yapzhenyie** [comment]
Please ensure the you download the plugin from SpigotMC not any other
websites. If the issue persists, please redownload the plugin from SpigotMC.

**Comment by baailey** [comment]
I'll try the newest version and see if that works fine.

**Comment by baailey** [comment]
Cannot reproduce on latest version.
