### ISSUE TITLE
GadgetsMenu v5.0.7 generated an exception

### ISSUE THREAD

**Issue by baailey** [yapzhenyie/GadgetsMenu#875]
**Describe the bug**
07.09 19:27:04 [Server] WARN [GadgetsMenu] Task #1603866 for GadgetsMenu v5.0.7 generated an exception
07.09 19:27:04 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.yapzhenyie.GadgetsMenu.nms.interfaces.entity.NMSArmorStand.isDeadNMS()" because "<local1>" is null
07.09 19:27:04 [Server] INFO at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetFlowerGiver.lambda$1(GadgetFlowerGiver.java:190) ~[GadgetsMenu.jar:?]
07.09 19:27:04 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
07.09 19:27:04 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
07.09 19:27:04 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1550) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
07.09 19:27:04 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:482) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
07.09 19:27:04 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1465) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
07.09 19:27:04 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1261) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
07.09 19:27:04 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
07.09 19:27:04 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

**Further Information (please complete the following information):**
 - Server Version: git-Airplane-"ec7d3d0" (MC: 1.17.1)
 - GadgetsMenu Version: 5.0.7

**Comment by yapzhenyie** [comment]
Please ensure your paper fork server is up to date.
