### ISSUE TITLE
Equipping Baby Black & White Pet Rabbit CRASHES The Server

### ISSUE THREAD

**Issue by Daine-Gostas** [yapzhenyie/GadgetsMenu#877]
Describe the bug:
The bug basically crashes my server every time I try to equip the baby black and white rabbit.

To Reproduce:
1. Go to GadgetsMenu GUI, pets.
2. Click on Black and White Rabbit, Baby.
3. The server crashes.

Expected behavior:
I expect to spawn the baby rabbit next to me, but the server crashes.

Further Information (please complete the following information):
 - Server Version: [1.17.1]
 - GadgetsMenu Version: [5.0.7]
 - Console stack trace if have.

Additional Information:
The server has to be reset manually and the GadgetsMenu plugin data deleted.

**Comment by yapzhenyie** [comment]
I recommend you to switch your server to paper instead of spigot.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
