### ISSUE TITLE
Cannot edit Lore values for some categories...

### ISSUE THREAD

**Issue by Raesak** [yapzhenyie/GadgetsMenu#878]
Minecraft: 1.17.1
Paper: 257
GM: 5.0.7

When I make edits to the lore values for categories: animatedhats.yml, banners.yml, hats.yml
it doesn't save properly after reloading the plugin OR restarting the server.

For example if I type something and save it ("Test" for the sake of example):
https://i.postimg.cc/kX9g6v4J/Screenshot-2021-09-09-201814.jpg

After I save it and restart the server (or reload the plugin):
https://i.postimg.cc/zXjXnHbn/Screenshot-2021-09-09-202028.jpg

**Comment by yapzhenyie** [comment]
You are supposed to configure the lore like this
```
Lore:
  Locked:
  - 'line 1'
  - 'line 2'
```

**Comment by Raesak** [comment]
Right. I forgot to mention I tested with list format as well. The same problem occurred.
Same result using either single quotes or double quotes.

Before reloading plugin/restarting server:
https://i.postimg.cc/pThK3xFk/Screenshot-2021-09-09-224733.jpg

After reloading plugin/restarting server:
https://i.postimg.cc/63kCXSVK/Screenshot-2021-09-09-224820.jpg

**Comment by yapzhenyie** [comment]
> Right. I forgot to mention I tested with list format as well. The same problem occurred.
> Same result using either single quotes or double quotes.
> 
> Before reloading plugin/restarting server:
> https://i.postimg.cc/pThK3xFk/Screenshot-2021-09-09-224733.jpg
> 
> After reloading plugin/restarting server:
> https://i.postimg.cc/63kCXSVK/Screenshot-2021-09-09-224820.jpg

It works. You can do the same thing in the Unlocked section, then you will see the result in-game.
