### ISSUE TITLE
Horse pets are bugged (More details)

### ISSUE THREAD

**Issue by Raesak** [yapzhenyie/GadgetsMenu#879]
Minecraft: 1.17.1
Paper: 257
GM: 5.0.7

I haven't tested ALL of the horse type pets, but more than a few. The same issue happens with all that I tested (including Donkey, Skeleton horse, ETC).

When riding the horse, the audio for the horse will desync from where you actually see the horse.
When dismounting the horse, there is a weird rubber band effect which makes you dismount at a previous location (possibly relating to the desynced audio?).
Also sometimes after dismounting the horse, the horse will stay far away from you and move around as if it's following you at a distance, until you run close enough to the horse to get it to teleport to your location.

Here's a video showing what I'm talking about:
https://www.youtube.com/watch?v=Cc-PzHmfe5U&ab_channel=Kasear

**Comment by Raesak** [comment]
I just saw that this has been reported already, and has been known even before that.




Oh well.

**Comment by Raesak** [comment]
I just saw that this has been reported already.
In any case, my report covers more details than the other one.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
