### ISSUE TITLE
Too many packets

### ISSUE THREAD

**Issue by srnyx** [yapzhenyie/GadgetsMenu#881]
**Describe the bug**
When riding a horse it kicks the user

**To Reproduce**
1. Spawn a horse pet
2. Ride it

**Further Information (please complete the following information):**
 - Server Version: 1.17.1
 - GadgetsMenu Version: 5.0.7
 - https://paste.srnyx.xyz/ulehehezol.properties

**Screenshots**
![img](https://img.srnyx.xyz/r/kua8yrw0o9a.png)

**Comment by yapzhenyie** [comment]
I can't reproduce the same issue from my side. May I know what server you're using? spigot/paper

**Comment by srnyx** [comment]
> May I know what server you're using? spigot/paper

Purpur 1.17.1. And it may have something to do with ViaVersion/ViaBackwards/ViaRewind/ViaRewind Legacy Support, although I'm using the same version as the server.

Also, it only happens with horses (and maybe other mobs that are rideable in vanilla), so maybe it has something to do with that.

**Comment by srnyx** [comment]
Figured out this is unrelated to GadgetsMenu
