### ISSUE TITLE
Custom main menu

### ISSUE THREAD

**Issue by SlinkayeCodes** [yapzhenyie/GadgetsMenu#886]
It would be cool if you could customize the main menu, like feature items that aren't actually categories, but there to make the main menu more compact.

**Comment by yapzhenyie** [comment]
Currently you can't do that in GadgetsMenu. As an alternative, you can use some other custom menu plugin to achieve it.

**Comment by yapzhenyie** [comment]
You can now create custom items in the main menu. Check out our premium version for more details.
