### ISSUE TITLE
Mystery boxes expiring

### ISSUE THREAD

**Issue by elaineandsparky** [yapzhenyie/GadgetsMenu#887]
Our players are given mystery boxes in kits through console commands. These boxes are expiring despite no expiry date in the configs from what I can find (premium version)

  Types:
    Normal-Mystery-Box:
      Name: '&aUnicorn Box'
      Material: ENDER_CHEST
      Lore:
        Expiry-Date: '&cExpires in {EXPIRY_DATE}'
        Never-Expired: '&7This has no expiration date.'
        Quality:
          One-Star:
          - '&7This box contains one of the following:'
          - ''
          - '&aCommon {ITEM_ONE}'
          - '&aCommon {ITEM_TWO}'
          - '&aCommon {ITEM_THREE}'
          - '&aCommon {ITEM_FOUR}'
          - '&9Rare {ITEM_FIVE}'
          - '&5Epic {ITEM_SIX}'
          - '&6Legendary {ITEM_SEVEN}'
          - ''
          - '&7Quality: &e✰&7✰✰✰✰'
          - '{EXPIRY_DATE}'
          - ''
          - '&eClick to open!'
          Two-Star:
          - '&7This box contains one of the following:'
          - ''
          - '&aCommon {ITEM_ONE}'
          - '&aCommon {ITEM_TWO}'
          - '&aCommon {ITEM_THREE}'
          - '&9Rare {ITEM_FOUR}'
          - '&9Rare {ITEM_FIVE}'
          - '&5Epic {ITEM_SIX}'
          - '&6Legendary {ITEM_SEVEN}'
          - ''
          - '&7Quality: &e✰✰&7✰✰✰'
          - '{EXPIRY_DATE}'
          - ''
          - '&eClick to open!'
          Three-Star:
          - '&7This box contains one of the following:'
          - ''
          - '&aCommon {ITEM_ONE}'
          - '&aCommon {ITEM_TWO}'
          - '&9Rare {ITEM_THREE}'
          - '&9Rare {ITEM_FOUR}'
          - '&5Epic {ITEM_FIVE}'
          - '&5Epic {ITEM_SIX}'
          - '&6Legendary {ITEM_SEVEN}'
          - ''
          - '&7Quality: &e✰✰✰&7✰✰'
          - '{EXPIRY_DATE}'
          - ''
          - '&eClick to open!'
          Four-Star:
          - '&7This box contains one of the following:'
          - ''
          - '&aCommon {ITEM_ONE}'
          - '&9Rare {ITEM_TWO}'
          - '&5Epic {ITEM_THREE}'
          - '&5Epic {ITEM_FOUR}'
          - '&6Legendary {ITEM_FIVE}'
          - '&6Legendary {ITEM_SIX}'
          - '&6Legendary {ITEM_SEVEN}'
          - ''
          - '&7Quality: &e✰✰✰✰&7✰'
          - '{EXPIRY_DATE}'
          - ''
          - '&eClick to open!'
          Five-Star:
          - '&7This box contains one of the following:'
          - ''
          - '&9Rare {ITEM_ONE}'
          - '&5Epic {ITEM_TWO}'
          - '&5Epic {ITEM_THREE}'
          - '&6Legendary {ITEM_FOUR}'
          - '&6Legendary {ITEM_FIVE}'
          - '&6Legendary {ITEM_SIX}'
          - '&6Legendary {ITEM_SEVEN}'
          - ''
          - '&7Quality: &e✰✰✰✰✰'
          - '{EXPIRY_DATE}'
          - ''
          - '&eClick to open!'

![image](https://user-images.githubusercontent.com/69724087/139634928-e7946a6d-500f-4da2-ad2e-f64529959101.png)

**Comment by yapzhenyie** [comment]
The expiry date of the mystery box is configure in the command. Please look for this <https://github.com/yapzhenyie/GadgetsMenu/wiki/Commands#gmysteryboxes-give-player-amount-quality-ex7hdmfalse-reqpermfalse-cqualitychances>

**Comment by elaineandsparky** [comment]
is that new? as i never had to do this on another server I owned and don't recall having this problem.
Is it possible to have it set in configs as this isn't very user friendly

**Comment by yapzhenyie** [comment]
By default, mystery box will have 7 days of expiry date and there is no way to change the default value in config file. The only way to do that is add a parameter in the command when you give player mystery boxes.
