### ISSUE TITLE
Can't use things in menu

### ISSUE THREAD

**Issue by llt12213** [yapzhenyie/GadgetsMenu#889]
as title says,when my players open a box,the message will show them and they will auto-wear the costumes,but they cant use them in the menu ,like this
[![I3ecQg.png](https://z3.ax1x.com/2021/11/07/I3ecQg.png)](https://imgtu.com/i/I3ecQg)
[![I3egyQ.png](https://z3.ax1x.com/2021/11/07/I3egyQ.png)](https://imgtu.com/i/I3egyQ)
could pls help me?
also im a chinese :)

**Comment by yapzhenyie** [comment]
> as title says,when my players open a box,the message will show them and they will auto-wear the costumes,but they cant use them in the menu ,like this [![I3ecQg.png](https://camo.githubusercontent.com/a8f34a2929a6b6a480200c8f2c579b727455407149a4f72429f5ea65678f8124/68747470733a2f2f7a332e617831782e636f6d2f323032312f31312f30372f4933656351672e706e67)](https://imgtu.com/i/I3ecQg) [![I3egyQ.png](https://camo.githubusercontent.com/00724a33b1ee635c271c06105499b1d27ecf195ac5a09739a4d9887f55971de8/68747470733a2f2f7a332e617831782e636f6d2f323032312f31312f30372f4933656779512e706e67)](https://imgtu.com/i/I3egyQ) could pls help me? also im a chinese :)

please refer to this.
https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from-mystery-boxes-but-they-still-cant-use-that-item
