### ISSUE TITLE
plz add Mystery box open in left click

### ISSUE THREAD

**Issue by AlexanderGG-0520** [yapzhenyie/GadgetsMenu#890]
On a server with geysermc installed, when BE connects to the server, the mystery box cannot be opened because mobile does not have the concept of right-clicking.
Also, the click type item is not found in Config.
Therefore, I would like to have a config that allows me to open the mystery box with a left click.

**Comment by yapzhenyie** [comment]
Please check this link
https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-why-can-non-op-players-not-open-the-mystery-vault
