### ISSUE TITLE
NMS Problem for the Rabbit Pet

### ISSUE THREAD

**Issue by Sulort** [yapzhenyie/GadgetsMenu#891]
Hi, there is an Error in the log file for the Rabbit Pet.
After a player joins the server this error occured.

We are using MC 1.17.1 paper-mc 380 and GadgetsMenu Premium Version 5.0.9

https://pastebin.com/NXzk1zkF

**Comment by yapzhenyie** [comment]
Sorry, the new update needs to be delayed until January 2022 as I do not have free time to fix the error and I need to concentrate on my final year project. Sorry for the inconvenience caused.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
