### ISSUE TITLE
Paintball Gadget Problem

### ISSUE THREAD

**Issue by Sulort** [yapzhenyie/GadgetsMenu#892]
After equipping yourself with the Paintball Gadget (diamond_horse_armor) and after using this Gadget, the changed Blocks ( colered terracotta blocks) are not changing back, so you can get these items for free :-)

![image](https://user-images.githubusercontent.com/44119820/143731682-8c988624-1cdf-4037-9ea5-3d260fb7841f.png)

There are also for each blockchange a  warning in the log file.
https://pastebin.com/73S21yJe

We are using MC 1.17.1 paper-mc 380 and GadgetsMenu Premium Version 5.0.9

**Comment by yapzhenyie** [comment]
Sorry, the new update needs to be delayed until January 2022 as I do not have free time to fix the error and I need to concentrate on my final year project. Sorry for the inconvenience caused.

This issue only happened in 1.17.1 for Paintball Gun Gadget and Mob Gun Gadget. For temporary fixes, you can disable these two gadget in `gadgets.yml` file until the new update is released.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
