### ISSUE TITLE
Tetherball Leash Bug

### ISSUE THREAD

**Issue by kacpiklPL** [yapzhenyie/GadgetsMenu#893]
Tetherball has a bug.
If you press the left mouse button on the leash, the leash will break and you can pick it up.

Would you like to block it?

![image](https://user-images.githubusercontent.com/5105795/144216456-3a0cf936-a9ed-4a92-9420-a5e4957abc97.png)
![image](https://user-images.githubusercontent.com/5105795/144216481-67cfbbcb-de0f-4816-bacc-5f7ffebb6a0f.png)

**Comment by yapzhenyie** [comment]
Sorry, the new update needs to be delayed until January 2022 as I do not have free time to fix the error and I need to concentrate on my final year project. Sorry for the inconvenience caused.

**Comment by kacpiklPL** [comment]
Will this be fixed in the new update?

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
