### ISSUE TITLE
Pets cannot be spawned and causes an error

### ISSUE THREAD

**Issue by baailey** [yapzhenyie/GadgetsMenu#901]
**Describe the bug**
When trying to spawn a pet, the pet will disappear and an error will appear in console.

**To Reproduce**
1. Open /gmenu main
2. Click to spawn a pet
3. Look in console

**Expected behavior**
The pet should spawn and follow you around.

**Further Information (please complete the following information):**
 - Server Version: git-Paper-66 (MC: 1.18)
 - GadgetsMenu Version: 5.1.1
 - https://mcpaste.io/3aba85615b59b05f

**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by yapzhenyie** [comment]
Please update your server to 1.18.1 build.

**Comment by baailey** [comment]
I'll be updating in a few hours. Will see how things go once on 1.18.1
