### ISSUE TITLE
Mystery Box with Armour Stands instead Hologram

### ISSUE THREAD

**Issue by PortugueseDream** [yapzhenyie/GadgetsMenu#902]
**Describe the bug**
When I leave the lobby and then re-join after playing in other world (without mystery boxes - like a duel) the mystery box's hologram is replaced by two armour stands

**To Reproduce**
1. Go to a lobby with Mystery Boxes
2. Join a minigame or gamemode
3. Return to lobby

**Expected behavior**
The Mystery Box's hologram is replaced by armour stands

**Further Information (please complete the following information):**
 - Server Version: [Paper 1.8.8]
 - GadgetsMenu Version: [latest]

**Screenshots**
![image](https://user-images.githubusercontent.com/81262586/147936348-d130fcad-287c-4ad1-a24a-d476871f2c39.png)

**Additional Information**
When I reload the plugin, the bug is fixed while I'm in the lobby

**Comment by yapzhenyie** [comment]
Any errors found in the console?

**Comment by PortugueseDream** [comment]
No, the only errors are these from Libs Disguises
![image](https://user-images.githubusercontent.com/81262586/147944134-7d0eaa80-26c9-4a2c-a086-47231bc98aec.png)

**Comment by yapzhenyie** [comment]
For version 1.8.8, you must use the specific version of ProtocolLib and Lib's Disguise.

https://github.com/yapzhenyie/GadgetsMenu/wiki/Morphs

**Comment by PortugueseDream** [comment]
Yes, I'm using the right version. I've just found the issue! It was an anticheat plugin 
Thank you for your help anyway!
