### ISSUE TITLE
shopping not working

### ISSUE THREAD

**Issue by MiniZombieYT** [yapzhenyie/GadgetsMenu#905]
**Describe the bug**
I want to buy an item, writes that I bought it, but it didn’t buy and won’t appear, you can always buy and spend mystical dust like that. error in console:Unknown command 

**To Reproduce**
1. opened the menu
2. I chose the item I want to buy (for mystic dust)
3. mystical dust was written off, but the item was not bought

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: Spigot 1.12.2
 - GadgetsMenu Version: 4.6.2
 - Console stack trace if have. Unknown command. Type "/help" for help. (written in console after purchase)

**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

downloaded and replaced files translated into Russian ( messages.yml, categories, mystery boxes, custom cosmetics)

sorry for the mistakes, i don't know english well

**Comment by yapzhenyie** [comment]
> **Describe the bug** I want to buy an item, writes that I bought it, but it didn’t buy and won’t appear, you can always buy and spend mystical dust like that. error in console:Unknown command
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. opened the menu
> 2. I chose the item I want to buy (for mystic dust)
> 3. mystical dust was written off, but the item was not bought
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Further Information (please complete the following information):**
> 
> * Server Version: Spigot 1.12.2
> * GadgetsMenu Version: 4.6.2
> * Console stack trace if have. Unknown command. Type "/help" for help. (written in console after purchase)
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional Information** Any other information that you would like to provide that may be relevant to the issue?
> 
> downloaded and replaced files translated into Russian ( messages.yml, categories, mystery boxes, custom cosmetics)
> 
> sorry for the mistakes, i don't know english well

Please check the link below and follow the steps.
<https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from-mystery-boxes-but-they-still-cant-use-that-item>

**Comment by MiniZombieYT** [comment]
> Please check the link below and follow the steps. https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from-mystery-boxes-but-they-still-cant-use-that-item

Thank you very much
