### ISSUE TITLE
Dont understand how to change permissions?

### ISSUE THREAD

**Issue by ChewieVR** [yapzhenyie/GadgetsMenu#906]
When people join my server, they cant acces the Gadgetsmenu (Enderchest).
But when I give them OP, it works. But I don't want to give the players OP, how do I fix this?

**Comment by yapzhenyie** [comment]
Please refer to the FAQ page.
https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-why-can-non-op-players-not-open-the-mystery-vault

**Comment by ChewieVR** [comment]
It is set to 0, they still cant open it.

**Comment by ChewieVR** [comment]
It is set to 0, they still cant open it.

**Comment by ChewieVR** [comment]
One of my friends just joined the server and he dosent spawn with a enderchest (Gadgetmenu)

**Comment by yapzhenyie** [comment]
So you're talking the menu item? You need to give the player `gadgetsmenu.menuselector` permission in order to get the menu item on join.
