### ISSUE TITLE
Plugin Broken on 1.18.2

### ISSUE THREAD

**Issue by TheCrafter8000** [yapzhenyie/GadgetsMenu#907]
**Describe the bug**
Plugin Does Not Load in 1.18.2.

**To Reproduce**
1. Install Plugin
2. Restart/Start Server
3. See error

**Expected behavior**
Plugin automatically disabled when loading.

**Further Information (please complete the following information):**
 - Server Version: [Paper 1.18.2]
 - GadgetsMenu Version: [4.6.2]

**Comment by yapzhenyie** [comment]
GadgetsMenu is now support 1.18.2, please check for new update.
