### ISSUE TITLE
Mystery Vault not opening

### ISSUE THREAD

**Issue by DisguisedTurtlee** [yapzhenyie/GadgetsMenu#909]
when i try to open the Mystery Vault as a **[Member]**  by right clicking it it doesn't open, but as a **OP** it opens normally
and i searched if there is like a permissions or smth but nah i couldn't find one

**Comment by yapzhenyie** [comment]
> when i try to open the Mystery Vault as a **[Member]** by right clicking it it doesn't open, but as a **OP** it opens normally and i searched if there is like a permissions or smth but nah i couldn't find one
Please refer to this link.
https://github.com/yapzhenyie/GadgetsMenu/issues/909#issue-1178382004

**Comment by DisguisedTurtlee** [comment]
wdym @yapzhenyie

**Comment by yapzhenyie** [comment]
my bad.
Please refer to this link.
https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-why-non-op-players-cannot-open-the-mystery-vault

**Comment by DisguisedTurtlee** [comment]
thank you <3
