### ISSUE TITLE
After opening the mystery box the gadget you get is not displayed in the menu.

### ISSUE THREAD

**Issue by Filitube** [yapzhenyie/GadgetsMenu#911]
Basically when a player goes to open the box and gets the gadget then he can't equip it because it is not obtained in the menu. Please help me!

**Comment by yapzhenyie** [comment]
Please refer to the FAQ.
<https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from-mystery-boxes-but-they-still-cant-use-that-item>
