### ISSUE TITLE
I can't see the mystery vault

### ISSUE THREAD

**Issue by Caldissimo** [yapzhenyie/GadgetsMenu#920]
**Describe the bug**
In the config file there are the coordinates for the mystery vault, but in game i can't see it, the only thing i can see in game is the hologram over the vault.

**Further Information (please complete the following information):**
 - Server Version: [Spigot 1.8.8]
 - GadgetsMenu Version: [latest].

**Comment by yapzhenyie** [comment]
The mystery vault can be any block. As long as you saw the hologram, you should be able to open the Mystery Vault menu via left or right click. 

If this does not help you, please provides a detail explanation of your issue.
