### ISSUE TITLE
Cosmetics

### ISSUE THREAD

**Issue by Pedroalegrias** [yapzhenyie/GadgetsMenu#925]
hello, I'm having a little problem with the plugin, it worked fine but players without op have access to all cosmetics, how do I fix this?

**Comment by yapzhenyie** [comment]
Please check your permission setup, make sure player don't have super permission which will grant them access all cosmetic items.

**Comment by yapzhenyie** [comment]
Please check your permission setup, make sure player don't have super
permission which will grant them access all cosmetic items.
