### ISSUE TITLE
 Consle spam causes by latest protocollib 

### ISSUE THREAD

**Issue by CloudeLecaw** [yapzhenyie/GadgetsMenu#927]
the latest version causes a massive console spam.
may because some packets changed in protocollib (Build 580+)
On spigot the latest version (Build 583) is recomment to use for 1.19 Servers

here the log from console.
https://pastebin.com/iicUxBFD

**Comment by yapzhenyie** [comment]
Please wait for newer update.

**Comment by yapzhenyie** [comment]
Duplicate of #926

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
