### ISSUE TITLE
[GadgetsMenu] Task #220 for GadgetsMenu v5.2.2 generated an exception java.lang.NoSuchMethodError: 'double net.minecraft.world.entity.Entity.dg()'    

### ISSUE THREAD

**Issue by pvpSmashMC** [yapzhenyie/GadgetsMenu#928]
Purpur 1.19.1
[GadgetsMenu] Task #220 for GadgetsMenu v5.2.2 generated an exception java.lang.NoSuchMethodError: 'double net.minecraft.world.entity.Entity.dg()'    - Spamming console.

https://pastebin.com/rqEy4d5c

Thank you! Latest protocolib and older versions don't work either!

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
