### ISSUE TITLE
[Free Version] MySql Unsynchronized Small Props

### ISSUE THREAD

**Issue by HansOffice** [yapzhenyie/GadgetsMenu#931]
After connecting to MySql, only the number of gift boxes were synchronized and no small props were synchronized, so clicking on it showed no permission
There is a reference to https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from- mystery-boxes-but-they-still-cant-use-that-item link, but it didn't solve the problem
![ME6 3WZ6IHLDXTS($C({`4P](https://user-images.githubusercontent.com/94523696/190873371-58c4f31e-d8b3-459d-a61e-40682cfde8a1.png)
![%2_~0QYB8PA9QRI8KA12R68](https://user-images.githubusercontent.com/94523696/190873375-c508933a-2d5c-4a4e-84f0-aff01d404029.png)
![ASI1{`XUDJX @X8LK~F6YA2](https://user-images.githubusercontent.com/94523696/190873376-82db2cb7-9b57-4ff3-9439-a11cb2ecbf92.png)
![IJX_9PA25XF6_ OHGRAfter connecting to MySql, only the number of gift boxes were synchronized and no small props were synchronized, so clicking on it showed no permission
There is a reference to https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from- mystery-boxes-but-they-still-cant-use-that-item link, but it didn't solve the problem
![ME6 3WZ6IHLDXTS($C({`4P](https://user-images.githubusercontent.com/94523696/190873371-58c4f31e-d8b3-459d-a61e-40682cfde8a1.png)
![%2_~0QYB8PA9QRI8KA12R68](https://user-images.githubusercontent.com/94523696/190873375-c508933a-2d5c-4a4e-84f0-aff01d404029.png)
![ASI1{`XUDJX @X8LK~F6YA2](https://user-images.githubusercontent.com/94523696/190873376-82db2cb7-9b57-4ff3-9439-a11cb2ecbf92.png)
}ZV](https://user-images.githubusercontent.com/94523696/190873378-ae4de6df-f387-4813-951c-e88f7f512cc6.png)

**Comment by HansOffice** [comment]
> 连接MySql后，只同步了礼盒数量，没有同步小道具，所以点击显示没有权限 有参考[https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-问题#q-player-had-purchased-a-cosmetic-item-or-gain-from-](https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from-) mystery-boxes-but-they-still-cant-use-that-item 链接，但它没有解决问题 ![ME6 3WZ6IHLDXTS($C({4P](https://user-images.githubusercontent.com/94523696/190873371-58c4f31e-d8b3-459d-a61e-40682cfde8a1.png) ![%2_~0QYB8PA9QRI8KA12R68](https:// user-images.githubusercontent.com/94523696/190873375-c508933a-2d5c-4a4e-84f0-aff01d404029.png) ![ASI1{XUDJX @X8LK~F6YA2](https://user-images.githubusercontent.com/94523696/190873376-82db2cb7-9b57-4ff3-9439-a11cb2ecbf92.png) ![IJX_9PA25XF6_ OHGR连接MySql后，只同步了礼盒数量，没有同步小道具，所以点击显示没有权限 有参考https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked -问题#q-player-had-purchased-a-cosmetic-item-or-gain-from-神秘盒-但他们仍然无法使用该项目链接，但它没有解决问题ME6 3WZ6IHLDXTS($C({4P](https://user-images.githubusercontent.com/94523696/190873371-58c4f31e-d8b3-459d-a61e-40682cfde8a1.png) ![%2_~0QYB8PA9QRI8KA12R68](https:// user-images.githubusercontent.com/94523696/190873375-c508933a-2d5c-4a4e-84f0-aff01d404029.png) ![ASI1{XUDJX @X8LK~F6YA2 }ZV](https://user-images.githubusercontent.com/94523696/190873378-ae4de6df-f387-4813-951c-e88f7f512cc6.png)
The remaining two pictures
![%2_~0QYB8PA9QRI8KA12R68](https://user-images.githubusercontent.com/94523696/190873419-edc55671-4939-4269-94b2-a4fb5b4fd896.png)


![ME6 3WZ6IHLDXTS($C({`4P](https://user-images.githubusercontent.com/94523696/190873439-1070a86c-4717-448d-8bec-8ab4f419508b.png)

**Comment by HansOffice** [comment]
The remaining two pictures
![%2_~0QYB8PA9QRI8KA12R68](https://user-images.githubusercontent.com/94523696/190873468-cdcbeecd-584d-44d3-a72e-b48a44d6be38.png)
![ME6 3WZ6IHLDXTS($C({`4P](https://user-images.githubusercontent.com/94523696/190873473-dc5005ac-8087-4d66-b885-5eb6bf844b85.png)

**Comment by yapzhenyie** [comment]
Did you update the `Execute-Command` in `config.yml` file?

**Comment by yapzhenyie** [comment]
For the free version, unlocked cosmetic items were saved inside your permissions plugin and does not handle by GadgetsMenu. To sync the permission between servers, your permissions plugin also need to enable MySQL database.

**Comment by HansOffice** [comment]
> 对于免费版本，解锁的化妆品保存在您的权限插件中，并且不由 GadgetsMenu 处理。要在服务器之间同步权限，您的权限插件还需要启用 MySQL 数据库。
I see, I just purchased the paid version and plan to replace it now

**Comment by HansOffice** [comment]
I see, I just purchased the paid version and plan to replace it now

**Comment by HansOffice** [comment]
> 对于免费版本，解锁的化妆品保存在您的权限插件中，并且不由 GadgetsMenu 处理。要在服务器之间同步权限，您的权限插件还需要启用 MySQL 数据库。

Is it possible to directly replace the translated configuration file of the Premium version with the compatible Premium version?

**Comment by yapzhenyie** [comment]
> > 对于免费版本，解锁的化妆品保存在您的权限插件中，并且不由 GadgetsMenu 处理。要在服务器之间同步权限，您的权限插件还需要启用 MySQL 数据库。
> 
> Is it possible to directly replace the translated configuration file of the Premium version with the compatible Premium version?

Sorry, I don't understand what you mean. Can you elaborate?

**Comment by HansOffice** [comment]
> > > 对于免费版本，您需要在数据库的保存权限插件中，而不是在 GadgetsMenu 。要在服务器之间同步权限，您的权限插件还需要启用 MySQL。
> > 
> > 
> > 是否可以直接用兼容的Premium版本替换Premium版本的翻译配置文件？
> 
> 对不起，我不明白你的意思。你能详细说明吗？

It is the file in this link https://www.dropbox.com/s/j6n9j91hbplp0wa/GadgetsMenu-Chinese.zip?dl=0. Can it be used in the premium version? Or do I need to do something extra?

**Comment by yapzhenyie** [comment]
Yes, you can directly replace the translation file. It is compatible with
the latest version. The plugin will update the configuration files
automatically.

**Comment by HansOffice** [comment]
> 是的，您可以直接替换翻译文件。它与最新版本兼容。该插件将自动更新配置文件。

Okay, thanks for the reply
