### ISSUE TITLE
[Advanced] There are some small props not synchronized after accessing mysql

### ISSUE THREAD

**Issue by HansOffice** [yapzhenyie/GadgetsMenu#932]
![OT)ONJG8DTUO{4OZ7ZD8Y03](https://user-images.githubusercontent.com/94523696/190889022-6a74d39e-025e-43b6-bdf3-8c75bf31da1f.png)
![)Y8K)(Z~5`H W)T9MF5BRG](https://user-images.githubusercontent.com/94523696/190889025-316efb79-dcf3-4b54-895f-15a9f112ec6a.png)
The same database that is accessed

**Comment by HansOffice** [comment]
Player-Data:
  Storage: mysql
  MySQL:
    hostname: localhost
    username: lh
    database: lh
    port: '3306'
    password: hans1101
    useSSL: false

Accessed databases

**Comment by yapzhenyie** [comment]
As mentioned earlier, you can access cosmetic items by granting user permission via permission plugin. The reason where two server has different unlocked cosmetic items is because different permission setup between two servers.

**Comment by HansOffice** [comment]
> 如前所述，您可以通过权限插件授予用户权限来访问化妆品。两台服务器有不同的解锁化妆品的原因是因为两台服务器之间的权限设置不同。

Do you still need both servers to use the same permission group plugin and the permission group plugin to create a database to make their data consistent?

**Comment by HansOffice** [comment]
> 如前所述，您可以通过权限插件授予用户权限来访问化妆品。两台服务器有不同的解锁化妆品的原因是因为两台服务器之间的权限设置不同。

Didn't you say that the paid version doesn't need a permission group plugin to sync? I'm already in the paid version

**Comment by yapzhenyie** [comment]
> > 如前所述，您可以通过权限插件授予用户权限来访问化妆品。两台服务器有不同的解锁化妆品的原因是因为两台服务器之间的权限设置不同。
> 
> Didn't you say that the paid version doesn't need a permission group plugin to sync? I'm already in the paid version

Yes, exactly. But your old data (the permissions added in your permissions plugin before using premium version) will not be synced into GadgetsMenu plugin.

Starting from the time you use premium version, unlock cosmetic items through mystery dust / open mystery boxes will be stored inside GadgetsMenu plugin.

**Comment by HansOffice** [comment]
> > > 如前所述，您可以通过权限用户权限来访问您的设备。两台服务器有不同的设置不同用户的原因是因为两台服务器之间的权限。
> > 
> > 
> > 不是说付费版不需要权限组插件同步吗？我已经是付费版了
> 
> 对，就是这样。但是您的旧数据（使用高级版本之前在您的权限插件中添加的权限）不会同步到 GadgetsMenu 插件中。
> 
> 从您使用高级版开始，通过神秘灰尘解锁化妆品/打开神秘盒子将存储在 GadgetsMenu 插件中。

What should I do to make the old data not get in the way of the new version of mysql, which I created separately, so what do I need to do to make it empty the old data and start using GadgetsMenu to record the data?

**Comment by yapzhenyie** [comment]
> > > > 如前所述，您可以通过权限用户权限来访问您的设备。两台服务器有不同的设置不同用户的原因是因为两台服务器之间的权限。
> > > 
> > > 
> > > 不是说付费版不需要权限组插件同步吗？我已经是付费版了
> > 
> > 
> > 对，就是这样。但是您的旧数据（使用高级版本之前在您的权限插件中添加的权限）不会同步到 GadgetsMenu 插件中。
> > 从您使用高级版开始，通过神秘灰尘解锁化妆品/打开神秘盒子将存储在 GadgetsMenu 插件中。
> 
> What should I do to make the old data not get in the way of the new version of mysql, which I created separately, so what do I need to do to make it empty the old data and start using GadgetsMenu to record the data?

clear all gadgetsmenu related permissions from your permissions plugin.

**Comment by HansOffice** [comment]
> > > > > 如前所述，您可以通过权限用户权限来访问您的设备。两台服务器有不同的设置不同的原因是因为两台服务器之间的权限。
> > > > 
> > > > 
> > > > 我已经不是付费版了？
> > > 
> > > 
> > > 您的对旧数据（使用高级在您的权限插件中的权限）不会同步 GadgetsMe 中
> > > 。存储在 GadgetsMenu 插件中。
> > 
> > 
> > 怎么做才能让旧数据不妨碍我单独创建的新版mysql，那么我需要怎么做才能让它清空旧数据并开始使用GadgetsMenu记录数据呢？
> 
> 从您的权限插件中清除所有与小工具菜单相关的权限。

Okay, I get it.
