### ISSUE TITLE
Exceptions - Paper 1.19.2, Build 174 and above

### ISSUE THREAD

**Issue by VimaMT** [yapzhenyie/GadgetsMenu#933]
Ever since Paper rewrote their chunk system with build 174 (and above), GadgetsMenu spams my console.

**To Reproduce**
1. Install any version of Paper 1.19.2 after their build 174
2. Install the latest version of GadgetsMenu Pro
3. Restart Server
4. See errors in console

**Expected behavior**
I hope to see no spam.

**Further Information (please complete the following information):**
 - Paper 1.19.2, Builds 174 and above
 - GadgetsMenu Premium Version: 5.2.5

**Screenshots**
28.09 11:22:17 [Server] INFO at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:386) ~[GadgetsMenu.jar:?]
28.09 11:22:17 [Server] INFO at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.NMSManagerImpl.spawnNMSArmorStand(NMSManagerImpl.java:145) ~[GadgetsMenu.jar:?]
28.09 11:22:17 [Server] INFO at com.yapzhenyie.GadgetsMenu.utils.mysteryvault.MysteryVault.createHolograms(MysteryVault.java:156) ~[GadgetsMenu.jar:?]
28.09 11:22:17 [Server] INFO at com.yapzhenyie.GadgetsMenu.tasks.UpdateHolograms.run(UpdateHolograms.java:36) ~[GadgetsMenu.jar:?]
28.09 11:22:17 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
28.09 11:22:17 [Server] WARN [GadgetsMenu] Task #186 for GadgetsMenu v5.2.5 generated an exception
28.09 11:22:17 [Server] INFO java.lang.NoSuchFieldError: P
28.09 11:22:17 [Server] INFO at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.NMSManagerImpl.addEntityToWorld(NMSManagerImpl.java:386) ~[GadgetsMenu.jar:?]
28.09 11:22:17 [Server] INFO at com.yapzhenyie.GadgetsMenu.nms.v1_19_R1.NMSManagerImpl.spawnNMSArmorStand(NMSManagerImpl.java:145) ~[GadgetsMenu.jar:?]
28.09 11:22:17 [Server] INFO at com.yapzhenyie.GadgetsMenu.utils.mysteryvault.MysteryVault.createIndividualHologram(MysteryVault.java:200) ~[GadgetsMenu.jar:?]
28.09 11:22:17 [Server] INFO at com.yapzhenyie.GadgetsMenu.utils.mysteryvault.MysteryVault.refreshIndividualHologram(MysteryVault.java:214) ~[GadgetsMenu.jar:?]
28.09 11:22:17 [Server] INFO at com.yapzhenyie.GadgetsMenu.tasks.UpdateIndividualHologram.run(UpdateIndividualHologram.java:32) ~[GadgetsMenu.jar:?]
28.09 11:22:17 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-177]
28.09 11:22:17 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Additional Information**
As soon as I put my older version of Paper back in I quit getting the exceptions.

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.

**Comment by VimaMT** [comment]
Thank you.
