### ISSUE TITLE
Custom Miniatures

### ISSUE THREAD

**Issue by FrancescoJacovo** [yapzhenyie/GadgetsMenu#934]
Hi, thanks for ur work. I'm a Network Owner and i think the miniatures can have more usage than the basic one. We have a Creators project and it'll be cool to add custom miniatures for theme, something specific, or maybe only social logos that follow the creator.

**Comment by yapzhenyie** [comment]
Thank you for raising this suggestion. This feature will be added in the next update.

**Comment by yapzhenyie** [comment]
This feature is already implemented in the latest version.
