### ISSUE TITLE
My luckperm isent working 

### ISSUE THREAD

**Issue by willemkoole** [yapzhenyie/GadgetsMenu#936]
I have the default installed on luckperms But I cant still not use the gadget tool and still not use the mystry box

When I try it keep saying 
You dont have the required permission gadgetsmenu.animation.none or this

gadgetsmenu.animation.normal

**Comment by yapzhenyie** [comment]
So have you give yourself the permission?

**Comment by willemkoole** [comment]
Witch prermission ?

**Comment by willemkoole** [comment]
![Uploading image.jpg…]()
`

**Comment by willemkoole** [comment]
I have it like this on my own and on the default Group

**Comment by yapzhenyie** [comment]
How many permissions plugin do you have in your server?

**Comment by willemkoole** [comment]
Only luckperms
