### ISSUE TITLE
My Players Do Not Receive The Items When They Open A Mysterybox!

### ISSUE THREAD

**Issue by NeoJSx** [yapzhenyie/GadgetsMenu#940]

**Comment by yapzhenyie** [comment]
Hi, can you refer to this FAQ page. Do reply to this message if your issue still persist.

https://github.com/yapzhenyie/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from-mystery-boxes-but-they-still-cant-use-that-item
