### ISSUE TITLE
Bug With GadGetsMenu

### ISSUE THREAD

**Issue by VoidNinjaaa** [yapzhenyie/GadgetsMenu#943]
[GadgetsMenu] Plugin GadgetsMenu v4.5.4 has failed to register events for class com.yapzhenyie.GadgetsMenu.listeners.EntityListener because org/bukkit/event/block/BlockExplodeEvent does not exist

Thats The Error And please fix

**Comment by VoidNinjaaa** [comment]
Using Spigot 1.8

**Comment by yapzhenyie** [comment]
Hi, GadgetsMenu is no longer support version 1.8.0, please update to version 1.8.8.

If you're unable to update your server version, do let me know and let me check is there an alternative solution for your case.

**Comment by VoidNinjaaa** [comment]
Sorry i dint read your message. I cant update to 1.8.8 tho. I Would really
like if ypu can help me. Thanks :)

Yap Zhen Yie ***@***.***> schrieb am Di., 14. Feb. 2023,
02:21:
