### ISSUE TITLE
Paintball Gun Gadget can be used to break blocks

### ISSUE THREAD

**Issue by baailey** [yapzhenyie/GadgetsMenu#945]
**Describe the bug**
When using the Paintball Gun Gadget, it can be used to break blocks, even in other WorldGuard regions that they don't have access to.

**To Reproduce**
1. Place Big Dripleafs in water
2. Fire a Paintball Gun Gadget at them

**Expected behavior**
For the Dripleaf to not break. I've even added Big and Small Dripleafs to the Blacklist yet they still get destroyed.

**Further Information (please complete the following information):**
 - Server Version: git-Paper-386 (MC: 1.19.3)
 - GadgetsMenu Version: 5.2.16

**Screenshots**
https://gfycat.com/ClosedCreepyGartersnake

**Additional Information**
N/A

**Comment by yapzhenyie** [comment]
Can you add this into the blacklist and see whether the issue is fixed?
`BIG_DRIPLEAF_STEM`

**Comment by baailey** [comment]
Still breaks

**Comment by yapzhenyie** [comment]
This issue will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
